# Generated by Django 5.0.7 on 2024-07-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode_id',
            field=models.CharField(default='', max_length=400),
        ),
    ]
